import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav>
          <a href="/apply" className="ttb-link">Apply</a> | <a href="/discover" className="ttb-link">Discover</a> | <a href="/matches" className="ttb-link">Matches</a> | <a href="/profile" className="ttb-link">Profile</a>
        </nav>
        <div className="ttb-container">
          {children}
        </div>
      </body>
    </html>
  );
}
